config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'brands#index', as: :authenticated_root
    end
    unauthenticated do
      root 'pages#home', as: :unauthenticated_root
    end
  end

  root 'pages#home'

  resources :users
  resources :brands do
    member do
      get :link_social_media
    end
    resources :campaigns do
      resources :tweets, only: [:index] do
        member do
          post :favorite
          post :unfavorite
          post :retweet
          post :unretweet
          post :follow
          post :unfollow
          get :reply
          post :post_reply
          get :comments
        end
        collection do
          post :order_by
          get :statistics, to: "twitter_statistics#index"
        end
      end
      resources :instagrams, only: [:index] do
        member do
          post :like
          post :unlike
          post :follow
          post :unfollow
          get :reply
          post :post_reply
          get :comments
        end
        collection do
          post :order_by
          get :statistics, to: "instagram_statistics#index"
        end
      end
      member do
        post :pull_tweets
        post :pull_instagrams
      end
    end
    resources :tweets, only: [:index] do
      member do
        post :favorite
        post :unfavorite
        post :retweet
        post :unretweet
        post :follow
        post :unfollow
        get :reply
        post :post_reply
        get :comments
      end
      collection do
        post :order_by
        get :statistics, to: "twitter_statistics#index"
      end
    end
    resources :instagrams, only: [:index] do
      member do
        post :like
        post :unlike
        post :follow
        post :unfollow
        get :reply
        post :post_reply
        get :comments
      end
      collection do
        post :order_by
        get :statistics, to: "instagram_statistics#index"
      end
    end
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  post 'contact_us' => 'pages#contact_us', as: :contact_us
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  layout "dashboard"

  before_filter :load_brands

  PER_PAGE = 10

  private
    def load_brands
      @brands = Brand.where(user_id: current_user.id)
    end

    def load_brand
      @brand = Brand.find(params[:brand_id] || params[:id]) 
    end

    def load_campaign
      @campaign = Campaign.find(params[:id])
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def is_dashboard?
     params[:controller] == "brands" && params[:action] == "index"
  end

  def is_brand?
    params[:controller] == "brands" && params[:action] != "index"
  end
end

app/views/shared/dashboard/_flash.html.haml
- message = ""
- flash_class = ""
- if flash[:notice].present?
  - message = flash[:notice]
  - flash_class = "alert-warning"
  - title = "Warning!"
- elsif flash[:error].present?
  - message = flash[:error]
  - flash_class = "alert-danger"
  - title = "Error!"
- elsif flash[:success].present?
  - message = flash[:success]
  - flash_class = "alert-success"
  - title = "Success!"

.alert.fresh-color.in#flash{class: flash_class}
  %button.close{"aria-label" => "Close", "data-dismiss" => "alert", type: "button"}
    %span{"aria-hidden" => "true"} ×
  %h4= title
  %p= message

= content_for :scripts do
  window.ectyon.shared.init_flash("#{message}");

app/views/shared/dashboard/_footer.html.haml
%footer.app-footer
  .wrapper.text-center
    © 2018 Copyright Ectyon

app/views/shared/dashboard/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top.navbar-top
  .container-fluid
    .navbar-header
      %button.navbar-expand-toggle{type: "button"}
        %i.fa.fa-bars.icon
      %ol.breadcrumb.navbar-breadcrumb
        %li
          = link_to "New Brand", new_brand_path, class: "btn btn-success"
      %button.navbar-right-expand-toggle.pull-right.visible-xs{type: "button"}
        %i.fa.fa-th.icon
    %ul.nav.navbar-nav.navbar-right
      %button.navbar-right-expand-toggle.pull-right.visible-xs{type: "button"}
        %i.fa.fa-times.icon
      %li.dropdown.profile
        %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", href: "#", role: "button"}
          = current_user.full_name
          %span.caret
        %ul.dropdown-menu.animated.fadeInDown
          %li.profile-img
            = image_tag(current_user.profile_image, class: "profile-img")
          %li
            .profile-info
              %h4.username= current_user.full_name
              %p= current_user.email
              .btn-group.margin-bottom-2x{:role => "group"}
                = link_to edit_user_path(current_user), class: "btn btn-default" do
                  %i.fa.fa-user
                  Profile
                = link_to destroy_user_session_path(), method: :delete, class: "btn btn-default" do
                  %i.fa.fa-sign-out
                  Logout

app/views/shared/dashboard/_left_navbar.html.haml
.side-menu.sidebar-inverse
  %nav.navbar.navbar-default{role: "navigation"}
    .side-menu-container
      .navbar-header
        = link_to brands_path, class: "navbar-brand" do
          .icon.fa.fa-paper-plane
          .title ectyon
        %button.navbar-expand-toggle.pull-right.visible-xs{type: "button"}
          %i.fa.fa-times.icon
      %ul.nav.navbar-nav
        %li{class: is_dashboard? ? "active" : ""}
          = link_to brands_path do
            %span.icon.fa.fa-tachometer
            %span.title Dashboard
        - @brands.each do |brand|
          %li.panel.panel-default.dropdown{class: is_brand? ? "active" : ""}
            %a{"data-toggle" => "collapse", href: "#dropdown-table-#{brand.id}"}
              %span.icon.fa.fa-table
              %span.title= brand.name
            .panel-collapse.collapse{id: "dropdown-table-#{brand.id}"}
              .panel-body
                %ul.nav.navbar-nav
                  %li= link_to "Edit Brand", edit_brand_path(brand)
                  - if brand.has_twitter_credentials?
                    %li= link_to "Tweets", brand_tweets_path(brand)
                    %li= link_to "Twitter Statistics", statistics_brand_tweets_path(brand)
                  - if brand.has_instagram_credentials?
                    %li= link_to "Instagrams", brand_instagrams_path(brand)
                    %li= link_to "Instagram Statistics", statistics_brand_instagrams_path(brand)
                  %li= link_to "Campaigns", brand_campaigns_path(brand)

app/views/shared/dashboard/_loader.html.haml
#loader.loader
  .loader-container.text-center.color-white
    %div
      %i.fa.fa-spinner.fa-pulse.fa-3x
    %div Loading